language: ruby
rvm:
 - "1.8.7"
 - "1.9.2"
 - "1.9.3"
 - rbx

branches:
 only:
  - master
  - gh-pages

script:
 - sass --update --sourcemap=none scss:styles --style compressed

before_install:
 - gem install sass