# Site settings
title: ZALORA styleguide
email: hi@zalora.com
description: >
  This is the ZALORA styleguide project.
  It collects and showcases everything design related to ensure brand consistency throughout the company
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost:3000" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Setup source and build directory
source: src
destination: dist
